### ISSUE TITLE
关于应用到新数据集

### ISSUE THREAD

**Issue by Palpitate18** [WangXFng/RDRec#2]
您好，我想在Amazon的其他种类数据集上应用您的方法，但在数据预处理的时候发现没有reviews_{dataset}.pickle文件，导致我没有办法生成explanation.json文件。请问您是否知道这个reviews_{dataset}.pickle文件应该从哪里获取或生成呢，感谢
![7967c300419d9cb9700355a9d11b294](https://github.com/user-attachments/assets/91dd9f96-f7d4-4cf7-b7cd-caf2b298c1b4)

**Comment by WangXFng** [comment]
你好～ 其实不要紧的，.pickle文件只是一个中间格式的数据。只要你能把现在有的数据，按照explanation.json文件的格式生成数据可以了。具体请看现有的几个explanation.json文件。每条数据需要哪几个字段还是挺清楚的。大概就是这样：
**explanation.json**
{
    "train": [
        {
            "user": 3,
            "item": 4,
            "explanation": "great quality",
            "feature": "quality"
        }],
    "val": [
        {
            "user": 3,
            "item": 4,
            "explanation": "great quality",
            "feature": "quality"
        }],
    "test": [
        {
            "user": 3,
            "item": 4,
            "explanation": "great quality",
            "feature": "quality"
        }]
}

**Comment by Palpitate18** [comment]
好的，谢谢您！是不是我使用GPT或者其他大模型从原始review文件中提取生成就可以哇

**Comment by WangXFng** [comment]
嗯。只要你能拿到这个explanation.json就不用去改代码了。蒸馏的过程你也可以用其他大模型来试试效果。加油

**Comment by Palpitate18** [comment]
好的，非常感谢！！！
