### ISSUE TITLE
AttributeError: 'super' object has no attribute 'beam_search'

### ISSUE THREAD

**Issue by blueColdSea** [WangXFng/RDRec#4]
when I run the following commend：
`python seq.py --data_dir ./data/toys/ --cuda --batch_size 32 --checkpoint ./checkpoints/Toys_seq_topN/`
the error is：
‘AttributeError: 'super' object has no attribute 'beam_search'

Could you help me with it？
Is the version of transformer wrong?

**Comment by WangXFng** [comment]
Yes. The function "beam_search" has been removed in the latest version. It has become an optional parameter for the function "generate".  Like this,

```
outputs = model.generate(
    input_ids,
    num_beams=num_beams,
    num_return_sequences=num_return_sequences,
    max_length=50,
    min_length=10,
    early_stopping=True
)
```

**The best choice is to create a new environment via Conda following the "requirement.txt" file.** Thank you for your question!

**Comment by blueColdSea** [comment]
Thanks for you patience！
This works for me：
`pip install transformers==4.36.2 -i https://pypi.python.org/simple`
