### ISSUE TITLE
在t_test.py中seq和topn的结果貌似搞反了

### ISSUE THREAD

**Issue by blueColdSea** [WangXFng/RDRec#5]
在[t_test.py](https://github.com/WangXFng/RDRec/blob/main/utils/t_test.py)这个文件中的seq和topn的结果和我跑出来的结果不一样
后面看了论文，才弄清楚是搞反了，论文中的结果才是对的

**Comment by WangXFng** [comment]
抱歉抱歉，我一直没注意到这个字段名。我稍后改正，谢谢你的提醒

**Comment by blueColdSea** [comment]
没事，我也是想让后面的人少踩坑

**Comment by WangXFng** [comment]
已改正，多谢提醒
